{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0db8ebf1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: cloudscraper in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (1.2.71)\n",
      "Requirement already satisfied: pyparsing>=2.4.7 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from cloudscraper) (3.0.9)\n",
      "Requirement already satisfied: requests>=2.9.2 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from cloudscraper) (2.31.0)\n",
      "Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from cloudscraper) (1.0.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from requests>=2.9.2->cloudscraper) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from requests>=2.9.2->cloudscraper) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from requests>=2.9.2->cloudscraper) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from requests>=2.9.2->cloudscraper) (2025.8.3)\n",
      "Requirement already satisfied: selenium in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (4.35.0)\n",
      "Requirement already satisfied: urllib3[socks]<3.0,>=2.5.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from selenium) (2.5.0)\n",
      "Requirement already satisfied: trio~=0.30.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from selenium) (0.30.0)\n",
      "Requirement already satisfied: trio-websocket~=0.12.2 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from selenium) (0.12.2)\n",
      "Requirement already satisfied: certifi>=2025.6.15 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from selenium) (2025.8.3)\n",
      "Requirement already satisfied: typing_extensions~=4.14.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from selenium) (4.14.1)\n",
      "Requirement already satisfied: websocket-client~=1.8.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from selenium) (1.8.0)\n",
      "Requirement already satisfied: attrs>=23.2.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio~=0.30.0->selenium) (25.3.0)\n",
      "Requirement already satisfied: sortedcontainers in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio~=0.30.0->selenium) (2.4.0)\n",
      "Requirement already satisfied: idna in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio~=0.30.0->selenium) (3.4)\n",
      "Requirement already satisfied: outcome in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio~=0.30.0->selenium) (1.3.0.post0)\n",
      "Requirement already satisfied: sniffio>=1.3.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio~=0.30.0->selenium) (1.3.1)\n",
      "Requirement already satisfied: cffi>=1.14 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio~=0.30.0->selenium) (1.15.1)\n",
      "Requirement already satisfied: wsproto>=0.14 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)\n",
      "Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)\n",
      "Requirement already satisfied: pycparser in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from cffi>=1.14->trio~=0.30.0->selenium) (2.21)\n",
      "Requirement already satisfied: h11<1,>=0.9.0 in c:\\users\\dbeye\\anaconda3\\lib\\site-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install cloudscraper\n",
    "!{sys.executable} -m pip install selenium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e0be3a5d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.5 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\DBeye\\AppData\\Local\\Temp\\ipykernel_41200\\2090167796.py\", line 13, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 39, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.5 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\DBeye\\AppData\\Local\\Temp\\ipykernel_41200\\2090167796.py\", line 13, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\dtypes\\dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.5 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\DBeye\\AppData\\Local\\Temp\\ipykernel_41200\\2090167796.py\", line 13, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\ops\\__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\ops\\array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\computation\\expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\computation\\check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\numexpr\\__init__.py\", line 24, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.5 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\DBeye\\AppData\\Local\\Temp\\ipykernel_41200\\2090167796.py\", line 13, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\arrays\\masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\core\\nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"c:\\Users\\DBeye\\anaconda3\\Lib\\site-packages\\bottleneck\\__init__.py\", line 7, in <module>\n",
      "    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    }
   ],
   "source": [
    "#get url response\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import urllib\n",
    "import cloudscraper\n",
    "import json\n",
    "import time\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.common.by import By\n",
    "\n",
    "#saves reviews in dataframe\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "3b5119c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#a means of connecting to a chrome server used to fully open the metacritic pages.\n",
    "cService = webdriver.ChromeService(executable_path=r'C:/Users/DBeye/Downloads/chromedriver-win64/chromedriver-win64/chromedriver.exe')\n",
    "\n",
    "#used to access the metaritic page.\n",
    "\n",
    "url = 'https://www.metacritic.com/game/crysis-3/critic-reviews/?platform=playstation-3'\n",
    "\n",
    "try:\n",
    "  driver = webdriver.Chrome(service=cService)\n",
    "  driver.get(url)\n",
    "\n",
    "  #code to maximize window for long enough to scrape all\n",
    "  # of the information.\n",
    "  driver.maximize_window()\n",
    "  time.sleep(10)\n",
    "  #code to scroll down the page; scroll_num will be adjusted based on the number of reviews.\n",
    "  scrollDown = 0\n",
    "  #determines how far to scroll down for each page.\n",
    "  scroll_num = 800\n",
    "  #scrolls down the page until it reaches the end.\n",
    "  while True:\n",
    "    scrollDown += 1\n",
    "    driver.execute_script(\"window.scrollBy(0,20)\")\n",
    "    if scrollDown > scroll_num:\n",
    "      break\n",
    "  time.sleep(20)\n",
    "\n",
    "finally:\n",
    "  html = driver.page_source\n",
    "  driver.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "021f01c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "#used to store review info.\n",
    "review_dict = {'publication':[], 'rating':[], 'date_published':[], 'quote':[], 'platform':[], 'url_link':[]}\n",
    "\n",
    "#used to parse the html code, find all of the review\n",
    "soup = BeautifulSoup(html, 'html.parser')\n",
    "\n",
    "#print(soup.find_all('div',class_=\"c-siteReview g-bg-gray10 u-grid g-outer-spacing-bottom-large\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f8789414",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nfor review in soup.find_all(\\'div\\', class_=\\'c-siteReview_main g-inner-spacing-medium\\'):\\n  #checks for reviews with \"Read More\" buttons.\\n  if review.find(\\'span\\', class_=\\'c-globalButton_label\\'):\\n    review_dict[\\'quote\\'].append(review.find(\\'span\\', class_=\\'c-globalButton_label\\').text)\\n    print(review.find(\\'span\\', class_=\\'c-globalButton_label\\').text)\\n  #checks for reviews without \"Read More\" buttons.\\n  else:\\n    review_dict[\\'quote\\'].append(review.find(\\'div\\',class_=\\'c-siteReview_quote g-outer-spacing-bottom-medium\\').find(\\'span\\').text)\\n    print(review.find(\\'div\\',class_=\\'c-siteReview_quote g-outer-spacing-bottom-medium\\').find(\\'span\\').text)\\n'"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "#used to store review info.\n",
    "review_dict = {}\n",
    "\n",
    "\n",
    "#used to parse the html code, find all of the review\n",
    "soup = BeautifulSoup(html, 'html.parser')\n",
    "\n",
    "\n",
    "#find all div elements containing the individual reviews.\n",
    "for index, review in enumerate(soup.find_all('div',class_=\"c-siteReview g-bg-gray10 u-grid g-outer-spacing-bottom-large\")):\n",
    "  #print(review)\n",
    "  review_info = {}\n",
    "  #checks for reviews with \"Read More\" buttons.\n",
    "  if review.find('div', class_='c-siteReview_quote g-outer-spacing-bottom-small'):\n",
    "    #print(review.find('span', class_='c-globalButton_label').text)\n",
    "    #print(review.find('div', class_='c-siteReview_quote g-outer-spacing-bottom-small').text)\n",
    "    review_info['quote'] = review.find('div', class_='c-siteReview_quote g-outer-spacing-bottom-small').text.replace(\",\",\"~\")\n",
    "  #checks for reviews without \"Read More\" buttons.\n",
    "  else:\n",
    "    review_info['quote'] = \"NO QUOTE\"\n",
    "  \n",
    "  #Adds the review publication to the dictionary.\n",
    "  if review.find('div',class_='c-siteReview_platform g-text-bold g-color-gray80 g-text-xsmall u-text-right u-text-uppercase'):\n",
    "    review_info['publication'] = review.find('a',class_='c-siteReviewHeader_publicationName g-text-bold g-color-gray90').text.replace(\",\",\"~\").replace(\"\\n    \",\"\").strip(\"  \")\n",
    "  else:\n",
    "    review_info['publication'] = \"NO PUBLICATION\"\n",
    "  \n",
    "  #Adds the numerical rating is available.\n",
    "  if review.find('div',class_='c-siteReviewScore_background c-siteReviewScore_background-critic_medium'):\n",
    "    review_info['rating'] = review.find('div',class_='c-siteReviewScore_background c-siteReviewScore_background-critic_medium').find('span').text\n",
    "  else:\n",
    "    review_info['rating'] = \"tbd\"\n",
    "  \n",
    "  #Adds the data published if available.\n",
    "  if review.find('div',class_='c-siteReview_reviewDate g-color-gray80 u-text-uppercase'):\n",
    "    #strips the empty spaces from the dates if they are found.\n",
    "    review_info['date_published'] = review.find('div',class_='c-siteReview_reviewDate g-color-gray80 u-text-uppercase').text.replace(\"\\n        \",\"\").replace(\"\\n      \",\"\")\n",
    "  else:\n",
    "    #case where we cannot find any date.\n",
    "    review_info['date_published'] = \"DATE NOT FOUND\"\n",
    "  \n",
    "  #Adds the platform if available.\n",
    "  if review.find('div',class_='c-siteReview_platform g-text-bold g-color-gray80 g-text-xsmall u-text-right u-text-uppercase'):\n",
    "    review_info['platform'] = review.find('div',class_='c-siteReview_platform g-text-bold g-color-gray80 g-text-xsmall u-text-right u-text-uppercase').text.replace(\",\",\"~\").replace(\"\\n      \",\"\").replace(\"\\n    \",\"\")\n",
    "  else:\n",
    "    review_info['platform'] = \"PLATFORM NOT FOUND\"\n",
    "\n",
    "  #adds the review link if available.\n",
    "  if review.find('a',class_='c-siteReview_externalLink g-color-gray80 u-flexbox u-flexbox-alignCenter u-text-whitespace-nowrap'):\n",
    "    review_info['url_link'] = review.find('a',class_='c-siteReview_externalLink g-color-gray80 u-flexbox u-flexbox-alignCenter u-text-whitespace-nowrap')['href']\n",
    "  else:\n",
    "    review_info['url_link'] = \"NO LINK\"\n",
    "  \n",
    "  review_dict[index+1] = review_info\n",
    "    #['href']\n",
    "\n",
    "\n",
    "\"\"\"\n",
    "for review in soup.find_all('div', class_='c-siteReview_main g-inner-spacing-medium'):\n",
    "  #checks for reviews with \"Read More\" buttons.\n",
    "  if review.find('span', class_='c-globalButton_label'):\n",
    "    review_dict['quote'].append(review.find('span', class_='c-globalButton_label').text)\n",
    "    print(review.find('span', class_='c-globalButton_label').text)\n",
    "  #checks for reviews without \"Read More\" buttons.\n",
    "  else:\n",
    "    review_dict['quote'].append(review.find('div',class_='c-siteReview_quote g-outer-spacing-bottom-medium').find('span').text)\n",
    "    print(review.find('div',class_='c-siteReview_quote g-outer-spacing-bottom-medium').find('span').text)\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "3d2d1a2b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "    \"1\": {\n",
      "        \"quote\": \"Despite the flaws~ Crysis 3 is a triumph that shows a willingness by Crytek to push itself to new heights~ achieving a beautiful three-way union of graphical fidelity~ compelling storytelling and a honed gameplay experience.[April 2013~ p68]\",\n",
      "        \"publication\": \"Playstation Official Magazine Australia\",\n",
      "        \"rating\": \"90\",\n",
      "        \"date_published\": \"Apr 3, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"NO LINK\"\n",
      "    },\n",
      "    \"2\": {\n",
      "        \"quote\": \"It\\u2019s the Crysis you know~ but with a few new strings to its bow. Not just a high water mark for graphics anymore.\",\n",
      "        \"publication\": \"Impulsegamer\",\n",
      "        \"rating\": \"88\",\n",
      "        \"date_published\": \"Mar 4, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.impulsegamer.com/ps3crysis3.html\"\n",
      "    },\n",
      "    \"3\": {\n",
      "        \"quote\": \"The console versions are still able to hold their own. We expected the six and seven year old circuitry in our PS3 and Xbox 360 to boil into a puddle of silicon soup as soon as we slipped the disc in the tray~ but as it turns out Crysis 3 runs well and looks fantastic no matter which platform you pick it up for.\",\n",
      "        \"publication\": \"IGN\",\n",
      "        \"rating\": \"85\",\n",
      "        \"date_published\": \"Feb 19, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.ign.com/articles/2013/02/19/crysis-3-review\"\n",
      "    },\n",
      "    \"4\": {\n",
      "        \"quote\": \"Though it\\u2019s still saddled with the plot baggage of its predecessors~ Crysis 3 is at least the most cohesive story in the series.\",\n",
      "        \"publication\": \"Game Informer\",\n",
      "        \"rating\": \"85\",\n",
      "        \"date_published\": \"Feb 19, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.gameinformer.com/games/crysis_3/b/ps3/archive/2013/02/19/crysis-3-review.aspx\"\n",
      "    },\n",
      "    \"5\": {\n",
      "        \"quote\": \"An excellent modern playground. Not only is it a beauty to behold~ it\\r\\nis also a pleasure to play. The capabilities of the nano suit can be\\r\\nused to its fullest in the giant playgrounds of the game. A game of\\r\\nhide and seek or tag has never been this sadistic. No other game\\r\\noffers the superhuman fun Crysis 3 offers.\",\n",
      "        \"publication\": \"InsideGamer.nl\",\n",
      "        \"rating\": \"85\",\n",
      "        \"date_published\": \"Feb 22, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.insidegamer.nl/recensies/103402/crysis-3-review\"\n",
      "    },\n",
      "    \"6\": {\n",
      "        \"quote\": \"All-in-all Crysis 3 is a great package~ despite burning bright half as long. It may have not been exactly what all the fans wanted~ but it does a great job of trying to appease as many as it can without sacrificing too much. Add to this a decent~ if not groundbreaking multiplayer suite and you have a solid FPS that is more than worth a look.\",\n",
      "        \"publication\": \"Console Monster\",\n",
      "        \"rating\": \"85\",\n",
      "        \"date_published\": \"Apr 8, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.consolemonster.com/article.php?id=0000001275\"\n",
      "    },\n",
      "    \"7\": {\n",
      "        \"quote\": \"Crysis 3 follows the trail of its predecessor to the letter. This means that we will again be experiencing the most astounding audiovisual experience~ which~ alongside its gameplay~ will constitute the main feature of this next-gen first person shooter. The experience may not be very innovative~ and the plot may not be very exciting~ but it remains on the top of the list of its genre regarding quality.\",\n",
      "        \"publication\": \"LaPS4\",\n",
      "        \"rating\": \"83\",\n",
      "        \"date_published\": \"Feb 25, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.laps3.com/analisis/374069-analisis_crysis_3.html\"\n",
      "    },\n",
      "    \"8\": {\n",
      "        \"quote\": \"If you're looking for a strong follow-up from the Crysis 2 storyline then you're going to be heaven. Crytek brings a very powerful story that fits just right with the previous titles and compliments it with a fast-paced gameplay experience. Sure the campaign might last 6-8 hours~ but you'll enjoy every minute of it.\",\n",
      "        \"publication\": \"Digital Chumps\",\n",
      "        \"rating\": \"82\",\n",
      "        \"date_published\": \"Feb 21, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://digitalchumps.com/game-reviews/35-ps3/10155-crysis-3.html\"\n",
      "    },\n",
      "    \"9\": {\n",
      "        \"quote\": \"Such is the strength of the online modes~ it lifts the overall package comfortably above the scant story offering. It pains my digits to write \\u2018technical tour de force\\u2019~ but it\\u2019s hard to describe Crysis 3 any other way. Though lacking soul in places~ this striking Prophet can still channel the divine.\",\n",
      "        \"publication\": \"Playstation Official Magazine UK\",\n",
      "        \"rating\": \"80\",\n",
      "        \"date_published\": \"Feb 19, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.officialplaystationmagazine.co.uk/review/crysis-3-ps3-review-stealthy-shooter-will-suits-you-sir/\"\n",
      "    },\n",
      "    \"10\": {\n",
      "        \"quote\": \"Crysis 3 is the best of its species. Technology and impressive graphics. But it isn't a surprise if you've played the previous game~ and this is quite short. The bow is fantastic and the new New York setting too~ but we wanted a more open and unexpected adventure.\",\n",
      "        \"publication\": \"Meristation\",\n",
      "        \"rating\": \"80\",\n",
      "        \"date_published\": \"Feb 21, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.meristation.com/es/playstation-3/analisis-juego/1770765\"\n",
      "    },\n",
      "    \"11\": {\n",
      "        \"quote\": \"Crysis 3 is a worthy sequel that is highly entertaining on a number of different levels.\",\n",
      "        \"publication\": \"PSX Extreme\",\n",
      "        \"rating\": \"80\",\n",
      "        \"date_published\": \"Feb 21, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.psxextreme.com/ps3-reviews/652.html\"\n",
      "    },\n",
      "    \"12\": {\n",
      "        \"quote\": \"Crysis 3 looks absolutely stunning. Strip away the graphics however and you are left with a mediocre shooter with some fancy gimmicks. The stealth gameplay saves the day.\",\n",
      "        \"publication\": \"XGN\",\n",
      "        \"rating\": \"80\",\n",
      "        \"date_published\": \"Feb 26, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.xgn.nl/ps3/review/43777/crysis-3/\"\n",
      "    },\n",
      "    \"13\": {\n",
      "        \"quote\": \"An action game in a sandbox. As usual~ the Nanosuit allows for interesting gameplay dynamics where both stealth and all out action are good approaches. There are also some interesting online game modes that makes good use of the Nanosuit's abilities.\",\n",
      "        \"publication\": \"Level7.nu\",\n",
      "        \"rating\": \"80\",\n",
      "        \"date_published\": \"Mar 12, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://level7.nu/texter/read.php?id=217206\"\n",
      "    },\n",
      "    \"14\": {\n",
      "        \"quote\": \"The beautiful and eerie locations give Crysis 3 a great atmosphere. Cowering in the tall grass~ while being hunted by bloodthirsty aliens~ reminded us of the terrifying raptor-scene from Jurassic Park. Blowing up a giant dam caused a spectacle big enough to make our inner vandal smile. [April 2013~ p.80]\",\n",
      "        \"publication\": \"Official PlayStation Magazine Benelux\",\n",
      "        \"rating\": \"80\",\n",
      "        \"date_published\": \"Apr 22, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"NO LINK\"\n",
      "    },\n",
      "    \"15\": {\n",
      "        \"quote\": \"Crysis 3 is set in a world that can take your breath away - but as an overall experience~ it's flawed. Crytek\\u2019s third installment is undoubtedly a beautiful product~ but it is not yet a beautiful game.\",\n",
      "        \"publication\": \"NZGamer\",\n",
      "        \"rating\": \"79\",\n",
      "        \"date_published\": \"Feb 25, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://nzgamer.com/ps3/reviews/1837/crysis-3.html\"\n",
      "    },\n",
      "    \"16\": {\n",
      "        \"quote\": \"Its attractive visuals make Crysis 3 a pleasure to look at~ and the game is plenty of fun~ though not up to the high standards of its forebears.\",\n",
      "        \"publication\": \"GameSpot\",\n",
      "        \"rating\": \"75\",\n",
      "        \"date_published\": \"Feb 19, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.gamespot.com/crysis-3/reviews/crysis-3-review-6404074/\"\n",
      "    },\n",
      "    \"17\": {\n",
      "        \"quote\": \"Psycho aside~ it\\u2019s hard to be engaged by the narrative~ and not only because it\\u2019s standard sci-fi fodder. Blatant clues as to the story\\u2019s direction mean most players will have pieced together the plot\\u2019s deeper mysteries long before they are formerly unveiled. Meanwhile~ optional audio logs that dig deeper into the lore can only be played via a static menu screen~ necessitating a break from the action to listen to a minute or two of laboured exposition.\",\n",
      "        \"publication\": \"games(TM)\",\n",
      "        \"rating\": \"70\",\n",
      "        \"date_published\": \"Mar 19, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.gamestm.co.uk/reviews/crysis-3-review/\"\n",
      "    },\n",
      "    \"18\": {\n",
      "        \"quote\": \"The appeal of the series has always been in its graphics and Crysis 3 still stands tall as one of the best looking console games of this generation. As many first person shooters shrivel up in the shadow of Call of Duty~ Crysis 3\\u2019s tactical gameplay and the introduction of the predator bow help it stand apart from the usual suspects of the genre. However~ seen as a series that pushed graphics and gameplay to the limits~ the third installment\\u2019s lack of innovation is perhaps its only weakness.\",\n",
      "        \"publication\": \"The Digital Fix\",\n",
      "        \"rating\": \"70\",\n",
      "        \"date_published\": \"Mar 21, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://gaming.thedigitalfix.com/content/id/1625/crysis-3.html\"\n",
      "    },\n",
      "    \"19\": {\n",
      "        \"quote\": \"Crysis 3 reunites the outfit with a voice~ Prophet~ and his supposed buddy~ Psycho and tells you that only one set of sentient long-johns can save the world. It\\u2019s a functional excuse for the action but uninspired~ much like the bulk of the game. [Issue#235]\",\n",
      "        \"publication\": \"Hyper Magazine\",\n",
      "        \"rating\": \"70\",\n",
      "        \"date_published\": \"Mar 28, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"NO LINK\"\n",
      "    },\n",
      "    \"20\": {\n",
      "        \"quote\": \"Sadly the PS3 version of Crysis 3 is the worst version compared to the other platforms. The PS3 version is filled with framedrops~ pop-ups~ audio glitches and disappointing graphics. The singleplayer is fine~ but it's short and the story is far from interesting. A fun shooter at best~ but certainly no more than that. If you want the best experience you\\u2019re better off with the Xbox or PC version.\",\n",
      "        \"publication\": \"PlaySense\",\n",
      "        \"rating\": \"65\",\n",
      "        \"date_published\": \"Feb 28, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.psx-sense.nl/111002/review-crysis-3/\"\n",
      "    },\n",
      "    \"21\": {\n",
      "        \"quote\": \"The problem is that in the few hours I spent online with the PlayStation 3 edition about a week after release the number of people playing at any one time seemed to hover around 700-800~ with the bulk of them engaged in death matches rather than any of the more interesting~ innovative game types (such as the new Hunter mode~ which pits a minority of nanosuit-wearing~ permanently cloaked hunters against plain old human troopers).\",\n",
      "        \"publication\": \"Post Arcade (National Post)\",\n",
      "        \"rating\": \"65\",\n",
      "        \"date_published\": \"Mar 8, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://business.financialpost.com/2013/02/27/crysis-3-saving-the-world-from-aliens-one-arrow-at-a-time/\"\n",
      "    },\n",
      "    \"22\": {\n",
      "        \"quote\": \"Stunning to look at~ but the experience within its gorgeously rendered environments ultimately lacks substance. [Issue#230~ p.76]\",\n",
      "        \"publication\": \"Play UK\",\n",
      "        \"rating\": \"61\",\n",
      "        \"date_published\": \"Apr 23, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"NO LINK\"\n",
      "    },\n",
      "    \"23\": {\n",
      "        \"quote\": \"A devolution from open-world brilliance and a far cry from compelling~ Crysis 3 is a serviceable sci-fi shooter with noteworthy multiplayer and a story that just barely warrants attention.\",\n",
      "        \"publication\": \"PlayStation Universe\",\n",
      "        \"rating\": \"60\",\n",
      "        \"date_published\": \"Apr 1, 2013\",\n",
      "        \"platform\": \"PlayStation 3\",\n",
      "        \"url_link\": \"http://www.psu.com/a018929/Crysis-3-Review---Human-After-All\"\n",
      "    }\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "print(json.dumps(review_dict, indent=4))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "215aedbc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv \n",
    "\n",
    "csv_filename = \"crysis3-ps3.csv\"\n",
    "\n",
    "fieldnames = ['publication', 'rating', 'date_published', 'quote', 'platform', 'url_link']\n",
    "\n",
    "with open(csv_filename,mode='w',newline='') as file:\n",
    "  writer = csv.DictWriter(file,fieldnames=fieldnames)\n",
    "  writer.writeheader()\n",
    "  for r in review_dict:\n",
    "    writer.writerow({field: review_dict[r].get(field) or r for field in fieldnames})"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
